import type { Metadata } from "next";
 import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SessionProvider } from "next-auth/react";
import { PublicEnvScript } from "next-runtime-env";

import {  Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";
import LoadingScreen from "@/components/loading";
export const metadata: Metadata = {
  title: "Food Aapp",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "400", "700", "600", "800"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <PublicEnvScript />
      </head>

      <body
        className={`${poppins.className}  antialiased min-h-screen w-full bg-lightBgColor dark:bg-darkBgColor transition-all duration-500 ease-in-out`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider>{children}</SessionProvider>
          <Toaster />
          <LoadingScreen/>
        </ThemeProvider>
      </body>
    </html>
  );
}
